[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
v2 = "3o5FHxJVuU39wv7VSaYdewPosHLQzZGvPtdwnU4qYBiS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dhruvraj/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
